<%@ Page language="c#" Codebehind="MalformedTestPage.aspx.cs" AutoEventWireup="false" Inherits="NUnitAspTestPages.MalformedTestPage" %>
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN" >
<HTML>
	<HEAD>
		<title>MalformedTestPage</title>
		<meta name="GENERATOR" Content="Microsoft Visual Studio 7.0" />
		<meta name="CODE_LANGUAGE" Content="C#" />
		<meta name="vs_defaultClientScript" content="JavaScript" />
		<meta name="vs_targetSchema" content="http://schemas.microsoft.com/intellisense/ie5" />
	</HEAD>
	<body MS_POSITIONING="GridLayout">
		<form id="MalformedTestPage" method="post" runat="server">
			This page has malformed XHTML.
			<br>
			The DOCTYPE tag is missing a URL, the meta tags are missing their closing 
			slash (actually, they're not, because that's not supported yet, but they should be), and the br tag is missing its closing slash.
			<br>
			<br>
			It's typical of a page generated by Visual Studio .NET, and NUnitAsp must be to 
			test it.
			<br>
			<br>
			<p>
				One ASP.NET control is included so there's something to test against.
				<br>
				<asp:CheckBox id="control" Runat="server" Text="And here it is..."></asp:CheckBox>
			</p>
		</form>
	</body>
</HTML>
